void ChassisSet(int left, int right, bool immediate);

#define MOTOR_LIFT_REARRIGHT			1
#define MOTOR_LIFT_MIDDLELEFT			6
#define MOTOR_LIFT_MIDDLERIGHT			7
#define MOTOR_LIFT_FRONTLEFT			8
#define MOTOR_LIFT_FRONTRIGHT			9
#define MOTOR_LIFT_REARLEFT				10

#define MOTOR_CHASSIS_REARLEFT			2
#define MOTOR_CHASSIS_FRONTLEFT			3
#define MOTOR_CHASSIS_FRONTRIGHT		4
#define MOTOR_CHASSIS_REARRIGHT			5